DROP TABLE IF EXISTS wcf1_weather_warning_region;
CREATE TABLE wcf1_weather_warning_region (
    regionID INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    regionName VARCHAR(255) NOT NULL DEFAULT ''
);

INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Dithmarschen - Binnenland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Dithmarschen - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Nordfriesland - Binnenland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Nordfriesland - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Ostholstein - Binnenland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Ostholstein - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Pinneberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Insel Helgoland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Plön - Binnenland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Plön - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Rendsburg-Eckernförde - Binnenland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Rendsburg-Eckernförde - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Schleswig-Flensburg - Binnenland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Schleswig-Flensburg - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Cuxhaven - Binnenland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Cuxhaven - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Aurich - Binnenland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Aurich - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Friesland - Binnenland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Friesland - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Leer');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Insel Borkum');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Oldenburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Osnabrück');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Wesermarsch - Binnenland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Wesermarsch - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Wittmund - Binnenland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Wittmund - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Darmstadt-Dieburg und Stadt Darmstadt');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Offenbach');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Kassel');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Trier-Saarburg und Stadt Trier');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Kaiserslautern');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Rhein-Pfalz-Kreis und Stadt Ludwigshafen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Mainz-Bingen und Stadt Mainz');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Südwestpfalz und Stadt Pirmasens');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Heilbronn');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Karlsruhe');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Rhein-Neckar-Kreis und Stadt Heidelberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Enzkreis und Stadt Pforzheim');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Breisgau-Hochschwarzwald und Stadt Freiburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Alb-Donau-Kreis und Stadt Ulm');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt München');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Rosenheim');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Landshut');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Passau');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Straubing-Bogen und Stadt Straubing');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Regensburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Bamberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Bayreuth');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Coburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Hof');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Ansbach');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Fürth');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Aschaffenburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Schweinfurt');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Würzburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis und Stadt Augsburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Mecklenburgische Seenplatte - Nord');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Mecklenburgische Seenplatte - West');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Mecklenburgische Seenplatte - Südost');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Rostock - Binnenland Nord');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Rostock - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Rostock - Binnenland Süd');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Vorpommern-Rügen - Binnenland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Vorpommern-Rügen - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Vorpommern-Rügen - Insel Rügen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Nordwestmecklenburg - Binnenland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Nordwestmecklenburg - Küste');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Vorpommern-Greifswald - Binnenland Nord');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Vorpommern-Greifswald - Küste Nord');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Vorpommern-Greifswald - Binnenland Süd');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Vorpommern-Greifswald - Küste Süd');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Ludwigslust-Parchim - West');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Ludwigslust-Parchim - Ost');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Mittelsachsen - Tiefland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Mittelsachsen - Bergland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Vogtlandkreis - Tiefland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Vogtlandkreis - Bergland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Zwickau - Tiefland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Zwickau - Bergland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Bautzen - Tiefland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Bautzen - Bergland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Görlitz - Tiefland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Görlitz - Bergland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Sächsische Schweiz-Osterzgebirge - Tiefland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Sächsische Schweiz-Osterzgebirge - westelbisches Bergland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Sächsische Schweiz-Osterzgebirge - ostelbisches Bergland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Nordsachsen - Nord');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Nordsachsen - Süd');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Harz - Tiefland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Harz - Bergland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Flensburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Kiel');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Hansestadt Lübeck');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Neumünster');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Herzogtum Lauenburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Segeberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Steinburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Stormarn');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Hansestadt Hamburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Braunschweig');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Salzgitter');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Wolfsburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Gifhorn');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Goslar');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Helmstedt');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Northeim');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Peine');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Wolfenbüttel');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Göttingen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Region Hannover');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Diepholz');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Hameln-Pyrmont');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Hildesheim');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Holzminden');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Nienburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Schaumburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Celle');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Harburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Lüchow-Dannenberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Lüneburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Osterholz');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Rotenburg (Wümme)');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Heidekreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Stade');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Uelzen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Verden');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Delmenhorst');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Emden');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Wilhelmshaven');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Ammerland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Cloppenburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Emsland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Grafschaft Bentheim');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Vechta');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Hansestadt Bremen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Bremerhaven');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Düsseldorf');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Duisburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Essen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Krefeld');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Mönchengladbach');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Mülheim an der Ruhr');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Oberhausen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Remscheid');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Solingen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Wuppertal');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Kleve');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Mettmann');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Rhein-Kreis Neuss');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Viersen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Wesel');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Bundesstadt Bonn');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Köln');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Leverkusen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('StädteRegion Aachen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Düren');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Rhein-Erft-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Euskirchen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Heinsberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Oberbergischer Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Rheinisch-Bergischer Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Rhein-Sieg-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Bottrop');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Gelsenkirchen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Münster');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Borken');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Coesfeld');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Recklinghausen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Steinfurt');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Warendorf');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Bielefeld');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Gütersloh');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Herford');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Höxter');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Lippe');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Minden-Lübbecke');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Paderborn');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Bochum');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Dortmund');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Hagen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Hamm');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Herne');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Ennepe-Ruhr-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Hochsauerlandkreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Märkischer Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Olpe');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Siegen-Wittgenstein');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Soest');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Unna');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Frankfurt am Main');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Wiesbaden');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Bergstraße');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Groß-Gerau');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Hochtaunuskreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Main-Kinzig-Kreis und Stadt Hanau');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Main-Taunus-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Odenwaldkreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Rheingau-Taunus-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Wetteraukreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Gießen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Lahn-Dill-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Limburg-Weilburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Marburg-Biedenkopf');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Vogelsbergkreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Fulda');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Hersfeld-Rotenburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Schwalm-Eder-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Waldeck-Frankenberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Werra-Meissner-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Koblenz');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Ahrweiler');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Altenkirchen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Bad Kreuznach');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Birkenfeld');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Cochem-Zell');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Mayen-Koblenz');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Neuwied');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Rhein-Hunsrück-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Rhein-Lahn-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Westerwaldkreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Bernkastel-Wittlich');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Eifelkreis Bitburg-Prüm');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Vulkaneifel');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Frankenthal');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Landau in der Pfalz');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Neustadt an der Weinstraße');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Speyer');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Worms');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Zweibrücken');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Alzey-Worms');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Bad Dürkheim');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Donnersbergkreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Germersheim');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Kusel');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Südliche Weinstraße');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Stuttgart');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Böblingen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Esslingen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Göppingen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Ludwigsburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Rems-Murr-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Hohenlohekreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Schwäbisch Hall');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Main-Tauber-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Heidenheim');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Ostalbkreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Baden-Baden');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Rastatt');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Mannheim');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Neckar-Odenwald-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Calw');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Freudenstadt');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Emmendingen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Ortenaukreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Rottweil');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Schwarzwald-Baar-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Tuttlingen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Konstanz');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Lörrach');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Waldshut');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Reutlingen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Tübingen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Zollernalbkreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Biberach');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Bodenseekreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Ravensburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Sigmaringen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Ingolstadt');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Altötting');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Berchtesgadener Land');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Bad Tölz-Wolfratshausen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Dachau');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Ebersberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Eichstätt');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Erding');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Freising');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Fürstenfeldbruck');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Garmisch-Partenkirchen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Landsberg am Lech');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Miesbach');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Mühldorf a. Inn');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Neuburg-Schrobenhausen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Pfaffenhofen a.d. Ilm');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Starnberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Traunstein');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Weilheim-Schongau');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Deggendorf');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Freyung-Grafenau');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Kelheim');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Regen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Rottal-Inn');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Dingolfing-Landau');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Amberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Weiden in der Oberpfalz');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Amberg-Sulzbach');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Cham');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Neumarkt i.d. OPf.');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Neustadt a.d. Waldnaab');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Schwandorf');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Tirschenreuth');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Forchheim');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Kronach');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Kulmbach');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Lichtenfels');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Wunsiedel');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Erlangen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Nürnberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Schwabach');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Erlangen-Höchstadt');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Nürnberger Land');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Neustadt a.d. Aisch - Bad Windsheim');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Roth');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Weißenburg-Gunzenhausen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Bad Kissingen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Rhön-Grabfeld');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Haßberge');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Kitzingen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Miltenberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Main-Spessart');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Kaufbeuren');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Kempten (Allgäu)');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Memmingen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Aichach-Friedberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Dillingen a.d. Donau');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Günzburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Neu-Ulm');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Lindau (Bodensee)');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Ostallgäu');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Unterallgäu');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Donau-Ries');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Oberallgäu');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Regionalverband Saarbrücken');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Merzig-Wadern');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Neunkirchen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Saarlouis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Saarpfalz-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis St. Wendel');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Berlin');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Brandenburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Cottbus');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Frankfurt (Oder)');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Potsdam');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Barnim');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Dahme-Spreewald');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Elbe-Elster');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Havelland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Märkisch-Oderland');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Oberhavel');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Oberspreewald-Lausitz');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Oder-Spree');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Ostprignitz-Ruppin');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Potsdam-Mittelmark');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Prignitz');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Spree-Neiße');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Teltow-Fläming');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Uckermark');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Hansestadt Rostock');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Schwerin');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Chemnitz');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Erzgebirgskreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Dresden');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Meißen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Leipzig');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Leipzig');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Dessau-Roßlau');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Halle (Saale)');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Magdeburg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Altmarkkreis Salzwedel');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Anhalt-Bitterfeld');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Börde');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Burgenlandkreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Jerichower Land');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Mansfeld-Südharz');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Saalekreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Salzlandkreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Stendal');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Wittenberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Erfurt');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Gera');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Jena');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Suhl');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Weimar');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Stadt Eisenach');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Eichsfeld');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Nordhausen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Wartburgkreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Unstrut-Hainich-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kyffhäuserkreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Schmalkalden-Meiningen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Gotha');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Sömmerda');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Hildburghausen');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Ilm-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Weimarer Land');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Sonneberg');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Saalfeld-Rudolstadt');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Saale-Holzland-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Saale-Orla-Kreis');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Greiz');
INSERT INTO wcf1_weather_warning_region (regionName) VALUES ('Kreis Altenburger Land');